import re

mac = '001122334455'


# L'adresse MAC doit être en majuscule et séparée par des "-"
# On commence par séparer l'adresse MAC dans une list
listmac = re.findall('[a-fA-F0-9]{2}',mac)
# Puis on remet en string, séparée par "-"
mac = "-".join(listmac)
# On met en majuscule
mac = mac.upper()
# fichier de sortie
file = '/samba/winserv2016/' + mac + '.xml'


with open(file , 'w') as fichier:
	fichier.write('<?xml version="1.0" encoding="utf-8"?> \n')
	fichier.write('<unattend xmlns="urn:schemas-microsoft-com:unattend"> \n')
	fichier.write('<settings pass="windowsPE"> \n')
	fichier.write('<component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<SetupUILanguage> \n')
	fichier.write('<UILanguage>en-US</UILanguage> \n')
	fichier.write('</SetupUILanguage> \n')
	fichier.write('<InputLocale>0c09:00000409</InputLocale> \n')
	fichier.write('<SystemLocale>en-US</SystemLocale> \n')
	fichier.write('<UILanguage>en-US</UILanguage> \n')
	fichier.write('<UILanguageFallback>en-US</UILanguageFallback> \n')
	fichier.write('<UserLocale>en-US</UserLocale> \n')
	fichier.write('</component> \n')
	fichier.write('<component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<ImageInstall> \n')
	fichier.write('<OSImage> \n')
	fichier.write('<InstallTo> \n')
	fichier.write('<DiskID>0</DiskID> \n')
	fichier.write('<PartitionID>2</PartitionID> \n')
	fichier.write('</InstallTo> \n')
	fichier.write('</OSImage> \n')
	fichier.write('</ImageInstall> \n')
	fichier.write('<UserData> \n')
	fichier.write('<AcceptEula>true</AcceptEula> \n')
	fichier.write('<FullName>Administrateur</FullName> \n')
	fichier.write('<Organization>CastleIT</Organization> \n')
	fichier.write('<ProductKey> \n')
	fichier.write('<Key>WC2BQ-8NRM3-FDDYY-2BFGV-KHKQY</Key> \n')
	fichier.write('</ProductKey> \n')
	fichier.write('</UserData> \n')
	fichier.write('<EnableFirewall>true</EnableFirewall> \n')
	fichier.write('<DiskConfiguration> \n')
	fichier.write('  <Disk wcm:action="add"> \n')
	fichier.write('    <DiskID>0</DiskID>  \n')
	fichier.write('    <WillWipeDisk>true</WillWipeDisk>  \n')
	fichier.write('    <CreatePartitions> \n')
	fichier.write('      <!-- System partition --> \n')
	fichier.write('      <CreatePartition wcm:action="add"> \n')
	fichier.write('        <Order>1</Order>  \n')
	fichier.write('        <Type>Primary</Type>  \n')
	fichier.write('        <Size>350</Size>  \n')
	fichier.write('      </CreatePartition> \n')
	fichier.write('      <!-- Windows partition --> \n')
	fichier.write('      <CreatePartition wcm:action="add"> \n')
	fichier.write('        <Order>2</Order>  \n')
	fichier.write('        <Type>Primary</Type>  \n')
	fichier.write('        <Extend>true</Extend>  \n')
	fichier.write('      </CreatePartition> \n')
	fichier.write('    </CreatePartitions> \n')
	fichier.write('    <ModifyPartitions> \n')
	fichier.write('      <!-- System partition --> \n')
	fichier.write('      <ModifyPartition wcm:action="add"> \n')
	fichier.write('        <Order>1</Order>  \n')
	fichier.write('        <PartitionID>1</PartitionID>  \n')
	fichier.write('        <Label>System</Label>  \n')
	fichier.write('        <Letter>S</Letter>  \n')
	fichier.write('        <Format>NTFS</Format>  \n')
	fichier.write('        <Active>true</Active>  \n')
	fichier.write('      </ModifyPartition> \n')
	fichier.write('      <!-- Windows partition --> \n')
	fichier.write('      <ModifyPartition wcm:action="add"> \n')
	fichier.write('        <Order>2</Order>  \n')
	fichier.write('        <PartitionID>2</PartitionID>  \n')
	fichier.write('        <Label>Windows</Label>  \n')
	fichier.write('        <Letter>C</Letter>  \n')
	fichier.write('        <Format>NTFS</Format>  \n')
	fichier.write('      </ModifyPartition> \n')
	fichier.write('    </ModifyPartitions> \n')
	fichier.write('  </Disk> \n')
	fichier.write('  <WillShowUI>OnError</WillShowUI>  \n')
	fichier.write('</DiskConfiguration> \n')
	fichier.write('</component> \n')
	fichier.write('</settings> \n')
	fichier.write('<settings pass="offlineServicing"> \n')
	fichier.write('<component name="Microsoft-Windows-LUA-Settings" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<EnableLUA>false</EnableLUA> \n')
	fichier.write('</component> \n')
	fichier.write('</settings> \n')
	fichier.write('<settings pass="generalize"> \n')
	fichier.write('<component name="Microsoft-Windows-Security-SPP" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<SkipRearm>1</SkipRearm> \n')
	fichier.write('</component> \n')
	fichier.write('</settings> \n')
	fichier.write('<settings pass="specialize"> \n')
	fichier.write('<component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<InputLocale>040c:0000040c</InputLocale> \n')
	fichier.write('<SystemLocale>fr-FR</SystemLocale> \n')
	fichier.write('<UILanguage>fr-FR</UILanguage> \n')
	fichier.write('<UILanguageFallback>fr-FR</UILanguageFallback> \n')
	fichier.write('<UserLocale>fr-FR</UserLocale> \n')
	fichier.write('</component> \n')
	fichier.write('<component name="Microsoft-Windows-Security-SPP-UX" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<SkipAutoActivation>true</SkipAutoActivation> \n')
	fichier.write('</component> \n')
	fichier.write('<component name="Microsoft-Windows-SQMApi" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<CEIPEnabled>0</CEIPEnabled> \n')
	fichier.write('</component> \n')
	fichier.write('<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<ComputerName>WindowsPxe</ComputerName> \n')
	fichier.write('</component> \n')
	fichier.write('</settings> \n')
	fichier.write('<settings pass="oobeSystem"> \n')
	fichier.write('<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> \n')
	fichier.write('<AutoLogon> \n')
	fichier.write('<Password> \n')
	fichier.write('<Value>password</Value> \n')
	fichier.write('<PlainText>true</PlainText> \n')
	fichier.write('</Password> \n')
	fichier.write('<Enabled>true</Enabled> \n')
	fichier.write('<Username>Administrateur</Username> \n')
	fichier.write('</AutoLogon> \n')
	fichier.write('<OOBE> \n')
	fichier.write('<HideEULAPage>true</HideEULAPage> \n')
	fichier.write('<HideLocalAccountScreen>true</HideLocalAccountScreen> \n')
	fichier.write('<HideOEMRegistrationScreen>true</HideOEMRegistrationScreen> \n')
	fichier.write('<HideOnlineAccountScreens>true</HideOnlineAccountScreens> \n')
	fichier.write('<HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE> \n')
	fichier.write('<NetworkLocation>Work</NetworkLocation> \n')
	fichier.write('<ProtectYourPC>1</ProtectYourPC> \n')
	fichier.write('<SkipMachineOOBE>true</SkipMachineOOBE> \n')
	fichier.write('<SkipUserOOBE>true</SkipUserOOBE> \n')
	fichier.write('</OOBE> \n')
	fichier.write('<UserAccounts> \n')
	fichier.write('<AdministratorPassword> \n')
	fichier.write('<Value>password</Value> \n')
	fichier.write('<PlainText>true</PlainText> \n')
	fichier.write('</AdministratorPassword> \n')
	fichier.write('<LocalAccounts> \n')
	fichier.write('<LocalAccount wcm:action="add"> \n')
	fichier.write('<Description>Administrateur</Description> \n')
	fichier.write('<DisplayName>Administrateur</DisplayName> \n')
	fichier.write('<Group>Administrators</Group> \n')
	fichier.write('<Name>Administrateur</Name> \n')
	fichier.write('</LocalAccount> \n')
	fichier.write('</LocalAccounts> \n')
	fichier.write('</UserAccounts> \n')
	fichier.write('<RegisteredOrganization>CastleIT</RegisteredOrganization> \n')
	fichier.write('<RegisteredOwner>Administrateur</RegisteredOwner> \n')
	fichier.write('<DisableAutoDaylightTimeSet>false</DisableAutoDaylightTimeSet> \n')
	fichier.write('<TimeZone>Romance Standard Time</TimeZone> \n')
	fichier.write('</component> \n')
	fichier.write('</settings> \n')
	fichier.write('</unattend> \n')
